---
- name: Provision server to prepare for the actual deployment
  hosts: web
  remote_user: provisioner
  become: true
  tasks:

    - name: Install various packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Add user 'buildout' and disable its password
      ansible.builtin.user:
        name: buildout
        password: '*'
        state: present
        shell: "/bin/bash"
        groups: docker

    - name: Add maintainers' ssh keys so they can log in as user buildout.
      ansible.posix.authorized_key:
        user: buildout
        key: {% raw %}https://github.com/{{ item }}.keys{% endraw %}
      with_items:
        - reinout
        # TODO: add more maintainers

    - name: Create dir inside /srv for the checkout
      ansible.builtin.file:
        path: {% raw %}/srv/{{ site_name }}{% endraw %}
        state: directory
        mode: "0755"
        owner: buildout
        group: buildout
