# NENS_META_LEAVE_ALONE
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    assignees:
      - "reinout"
