default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
        pass_filenames: false
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
        exclude: '{{ cookiecutter.project_name }}'
  - repo: https://github.com/psf/black
    rev: '23.12.1'
    hooks:
      - id: black
        exclude: '{{ cookiecutter.project_name }}'
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        exclude: '{{ cookiecutter.project_name }}'
